exports.variants  = { 
  'ash grey': 'grey',
  'baby blue': 'blue',
  'aqua blue': 'blue',
  'black': 'black',
  'blue': 'blue',
  'blue grey': 'blue,grey',
  'bottle green': 'green',
  'brown': 'brown',
  'business blue': 'blue',
  'chocolate brown': 'brown',
  'cobalt blue': 'blue',
  'cool white': 'white,cream',
  'cornflower blue': 'blue',
  'crow black': 'black',
  'dark grey': 'black,grey',
  'green': 'green',
  'grey': 'grey',
  'island blue': 'blue',
  'light grey': 'grey',
  'light tan': 'tan,cream',
  'light-brown': 'tan,brown',
  'light-green': 'green',
  'midnight grey': 'grey,black',
  'mild grey': 'grey',
  'mustard brown': 'brown,tan',
  'navy': 'navy,blue',
  'navy blue': 'navy,blue',
  'orange': 'orange,red,yellow',
  'pale baby blue': 'blue',
  'pale blue': 'blue',
  'pastel green': 'green',
  'pear green': 'green',
  'red': 'red',
  'sand': 'cream,brown',
  'scarlet red': 'red',
  'shades of blue': 'blue',
  'silver': 'grey',
  'sky blue': 'blue',
  'sky blue and white': 'blue,white',
  'tufts blue': 'blue',
  'white': 'white,cream',
  'yellow': 'yellow',
  'baby pink': 'pink',
  'beige': 'brown,cream',
  'coco brown': 'brown',
  'olive green': 'green',
  'bluish black': 'black,blue',
  'pale green': 'green',
  'bubble gum pink': 'pink',
  'bussiness blue': 'blue',
  'butter yellow': 'yellow',
  'olive': 'green',
  'carrot orange': 'orange,red',
  'klein blue': 'blue',
  'citrus yellow': 'yellow,green',
  'crimson red': 'red',
  'dark brown': 'brown',
  'dark orange': 'orange,red',
  'dark violet': 'violet,purple,maroon',
  'ecru': 'brown,cream',
  'forest green': 'green',
  'prussian blue': 'blue',
  'peach': 'pink,orange',
  'hazelnut brown': 'brown',
  'indigo blue': 'blue',
  'lavender': 'purple,violet',
  'pearl white': 'white,cream',
  'light indigo blue': 'blue',
  'light island blue': 'blue',
  'light peach': 'pink,orange',
  'light pink': 'pink',
  'light prussian blue': 'blue',
  'light violet': 'purple,violet',
  'blue-grey': 'blue,grey',
  'sand castle': 'brown,cream',
  'mauve violet': 'violet,purple',
  'mulberry maroon': 'red,brown',
  'light blue': 'blue',
  'onion pink': 'pink',
  'pale klein blue': 'blue',
  'pale violet': 'violet,purple',
  'pale yellow': 'yellow',
  'light green': 'green',
  'peanut brown ': 'brown',
  'pink-red': 'pink,red',
  'reddish orange': 'orange,red',
  'rosewood maroon': 'red',
  ' sand castle brown': 'brown',
  'scottish green': 'green',
  'sea green': 'green',
  'seaspray green': 'green,blue',
  'biege': 'brown,tan,cream',
  'silver grey': 'grey',
  ' smoke blue': 'blue,grey',
  'steel blue': 'blue,grey',
  'turqoise blue': 'blue,green',
  '3shades of green': 'green',
  'mild yellow  ': 'yellow',
  'amazon green': 'green',
  'turmeric yellow': 'yellow,orange',
  'apple green': 'green',
  'ash blue': 'blue,grey',
  'army green': 'green',
  'light lavender': 'purple,violet',
  'baby fern green': 'green',
  'baby leave green': 'green',
  'baby orange': 'orange',
  'baby peach ': 'pink,orange',
  'baby yellow': 'yellow',
  'banana off-white': 'yellow,cream',
  'battle green': 'green',
  'beaver': 'brown',
  'beige black': 'black,cream',
  'berry red': 'red',
  'black-navy': 'black,blue',
  'charcoal grey': 'grey,black',
  'deep blue': 'blue',
  'neon orange': 'orange',
  'pastel yellow': 'yellow,cream',
  'blackish brown': 'black,brown',
  'blackish off-white': 'black,cream',
  'blood red': 'red',
  'sea-weed green': 'green',
  'pale turqoise': 'green,blue',
  'jet black': 'black',
  'dark-grey': 'grey,black',
  'brick red': 'red,orange',
  'bread white': 'white,cream',
  'bright green': 'green',
  'bright brown': 'brown',
  'bread off-white': 'white,cream',
  'brown vanilla': 'brown,cream',
  'bright orange': 'orange',
  'bright red': 'red',
  'bright sky blue': 'blue',
  'bright white': 'white',
  'british khaki ': 'tan,brown',
  'bronze': 'brown,black',
  'brown-white': 'brown',
  'brownish grey': 'brown,grey',
  'brownish off-white': 'brown,cream',
  'brownish white': 'brown,white',
  'bue-grey': 'blue,grey',
  'buff beige': 'brown,cream',
  'buff brown': 'brown,cream',
  'burgendy': 'red',
  'burgundy brown': 'red,brown',
  'butter cream': 'cream,yellow',
  'butter off-white': 'cream,yellow',
  'camel tan': 'tan,brown',
  'caramel brown': 'brown',
  'carolina blue': 'blue',
  'charcoal': 'grey,black',
  'charcoal brown': 'grey,black,brown',
  'choco brown': 'brown',
  'deep brown': 'brown',
  'cinnamon brown': 'brown',
  'classic black': 'black',
  'classic grey': 'grey',
  'cloud grey': 'grey,white',
  'gold yellow': 'yellow',
  'coco green': 'green',
  'cocoa brown': 'brown',
  'coffee brown': 'brown',
  'coin grey': 'grey',
  'copper': 'brown,red',
  'coral red': 'red',
  'corn': 'yellow',
  'corn tan': 'yellow,tan',
  'cream yellow': 'yellow,cream',
  'cowdung green': 'green',
  'light olive': 'green',
  'dark amazon green': 'green',
  'dark beige': 'tan,brown',
  'dark blue': 'blue',
  'dark bottle green': 'green',
  'khaki brown': 'brown',
  'mud brown': 'brown',
  'dark chocolate brown': 'brown',
  'dark cornflower blue': 'blue',
  'dark lovat': 'green,grey',
  'dark mauve violet': 'violet,purple,maroon',
  'dark military green': 'green',
  'dark navy': 'navy,blue',
  'dark navy blue': 'navy,blue',
  'dark olive': 'green',
  'dark olive green': 'green',
  'dark pink': 'pink',
  'dark prussian blue': 'blue',
  'dark purple': 'purple,violet',
  'dark sand ': 'cream,brown,tan',
  'dark resin': 'blue',
  'dark steel blue': 'blue',
  'dark teal green': 'green',
  'dark-blue': 'blue',
  'deep cowdung green': 'green',
  'denim blue': 'blue',
  'desert sand': 'brown,cream',
  'dim grey': 'grey,black',
  'dove grey': 'grey,white',
  'drab': 'brown',
  'drab british khaki': 'brown,tan',
  'dull orange': 'orange',
  'dull pink': 'pink',
  'dull white': 'white,cream',
  'earth brown': 'brown,tan',
  'ecru-vanilla brown': 'brown,cream',
  'emerald green': 'green',
  'emerald': 'green',
  'wine purple': 'purple,violet,red',
  'estate blue': 'blue',
  'fade beige ': 'cream,brown',
  'fade blue': 'blue',
  'fade brown': 'brown',
  'fade pink': 'pink',
  'faint blue fresco': 'blue',
  'fawn': 'cream,brown',
  'fern green': 'green',
  'fine white': 'white,cream',
  'florescent blue': 'blue',
  'fog grey': 'grey',
  'fuchsia': 'pink,violet,purple',
  'ginger tan': 'tan,brown',
  'glossy ecru': 'brown,cream',
  'gold': 'yellow',
  'gold yellow white': 'yellow,white,cream',
  'graphite green': 'green',
  'graphite grey': 'grey',
  'grass green': 'green',
  'greenish brown': 'green,brown',
  'greenish grey': 'green,grey',
  'grey white': 'grey,white',
  'grey-black': 'grey,black',
  'grey-cream': 'grey,cream',
  'rosewine pink': 'pink,red',
  'midnight-grey': 'grey,black',
  'greyish brown': 'brown,grey',
  'greyish navy': 'grey,blue',
  'greyish- cream': 'grey,cream',
  'greyish-black': 'grey,black',
  'grossgrain black': 'black',
  'ice blue': 'blue',
  'indigo': 'blue',
  'indigo blue and white': 'blue,white',
  'indigo blue white': 'blue,white',
  'ink black': 'black',
  'iron grey': 'grey',
  'khaki': 'tan,brown',
  'khaki green': 'tan,brown,green',
  'orange burst': 'orange,red,yellow',
  'lain cornflower blue': 'blue',
  'lemon green': 'green,yellow',
  'light ash blue': 'blue,grey',
  'light baby blue': 'blue',
  'light baby pink ': 'pink',
  'light blue grey': 'blue,grey',
  'light bondi blue': 'blue',
  'light brown ': 'brown,tan',
  'light business blue': 'blue',
  'light classic blue': 'blue',
  'light cobalt blue': 'blue',
  'light coco brown': 'brown',
  'light cornflower blue': 'blue',
  'light mauve violet': 'violet,purple',
  'light orange': 'orange',
  'light sky blue': 'blue',
  'light turmeric yellow': 'yellow,orange',
  'lilac': 'purple,violet',
  'lilac violet': 'violet,purple',
  'loden green': 'green',
  'lovat': 'green',
  'lovat green': 'green',
  'lustrous fine white': 'white',
  'mcd grey': 'grey',
  'metal grey': 'grey',
  'mid brown': 'brown',
  'mid grey': 'grey',
  'midnight black': 'grey,black',
  'midnight blue': 'grey,blue',
  'mild white': 'white',
  'military khaki brown': 'brown,tan',
  'milk white': 'white,cream',
  'moss green': 'green',
  'mulberry maroon ': 'red,brown',
  'mulberry purple': 'purple,violet',
  'mushroom brown': 'brown,tan',
  'natural ecru': 'cream,brown',
  'pale blue grey': 'blue,grey',
  'pale island blue': 'blue',
  'pale lavender': 'purple,violet',
  'pale light green ': 'green',
  'pale mauve violet': 'purple,violet',
  'pale pastel green': 'green',
  'pale sand': 'brown,cream',
  'pale seaspray green': 'green',
  'parakeet green': 'green',
  'pastel mint': 'green,blue',
  'peach beige': 'cream,brown,pink',
  'mustard seed yellow': 'yellow,cream',
  'pebble grey': 'grey',
  'pine green': 'green',
  'pink shaded green': 'pink,green',
  'pinkish maroon': 'pink,red',
  'plum': 'red',
  'plum maroon': 'red',
  'porcelain white': 'white,cream',
  'powder blue': 'blue',
  'pure white': 'white,cream',
  'putty': 'brown,tan',
  'reddish pink': 'pink,red',
  'reddish yellow': 'yellow,red',
  'resin maroon': 'red',
  'rib navy blue': 'navy,blue',
  'rich cream': 'cream',
  'rust': 'brown,red',
  'rusted brown': 'brown,red',
  'rusted red': 'brown,red',
  'rusty golden brown': 'brown,red,yellow',
  'sage': 'green,blue',
  'salmon pink': 'pink',
  'sand brown': 'brown,cream',
  'sand drab khaki': 'brown,cream,tan',
  'sea mist green': 'green,blue',
  'skin light tan': 'tan,brown,cream',
  'skin tan brown': 'tan,brown,cream',
  'sky and navy blue': 'blue,navy',
  'slate blue': 'blue',
  'slate grey': 'grey',
  'snow white': 'white,cream',
  'soft brown': 'brown,tan',
  'spring beige ': 'cream,brown',
  'stone': 'cream,brown',
  'stone grey': 'grey',
  'stone khaki': 'cream,brown',
  'stone off-white': 'cream,brown',
  'stone plain ': 'cream,brown',
  'straw yellow': 'yellow,cream',
  'sunset orange ': 'orange,yellow,red',
  'taupe': 'grey',
  'taupe brown': 'grey,brown',
  'tawny brown': 'brown',
  'tortilla brown': 'brown',
  'trunk brown': 'brown',
  'tuffs blue': 'blue',
  'turmeric brown': 'brown,orange,red',
  'umber brown ': 'brown',
  'vanilla white': 'cream,white',
  'warzone olive green': 'green',
  'water stone grey': 'grey,cream',
  'white-blue': 'white,blue',
  'yellow golden-tan ': 'yellow,tan',
  'yellow mustard seed': 'yellow',
  'yoke yellow': 'yellow' }